name: MyDog
main: dk.fido2603.mydog.MyDog
author: Fido2603
version: ${project.version}
api-version: 1.13
load: POSTWORLD
description: Tamed wolves but at least 10x better!
depend: []
softdepend: [Vault]
website: https://github.com/DoggyCraftDK/MyDog
commands:
   mydog:
      description: Command for the MyDog plugin
      usage: /<command> [help]
      aliases: [md, dog, dogs]
permissions:
    mydog.*:
        description: Gives access to all MyDog commands
        default: false
        children:
            mydog.all: true
    mydog.all:
        description: Gives access to all MyDog commands
        default: false
        children:
            mydog.teleport: true
            mydog.reload: true
            mydog.save: true
            mydog.help: true
            mydog.putdown: true
            mydog.dogs: true
            mydog.stats: true
            mydog.comehere: true
            mydog.rename: true
            mydog.free: true
            mydog.setid: true
    mydog.teleport:
        description: Player's tamed wolves will teleport to the player
        default: true
    mydog.help:
        description: Player can view the MyDog command list
        default: true
    mydog.putdown:
        description: Player can kill their Dog with a command
        default: true
    mydog.comehere:
        description: Player can force their Dogs to load and teleport to the position of the player
        default: true
    mydog.dogs:
        description: Player can get an overview about their Dogs
        default: true
    mydog.stats:
        description: Player can view stats about their Dogs
        default: true
    mydog.rename:
      description: Player can rename their Dogs
      default: true
    mydog.setid:
      description: Player can set a custom ID to their Dogs
      default: true
    mydog.free:
        description: Player can set their Dogs free
        default: true
    mydog.reload:
        description: Player can reload the configuration(s)
        default: false
    mydog.save:
        description: Player can save the configuration(s)
        default: false       
